#!/bin/bash

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    echo 'Removing database and user...'
    mysql -u'root' -e'DROP USER IF EXISTS qstats2@localhost;'
    mysql -u'root' -e'DROP DATABASE IF EXISTS qstats2;'
    mysql -u'root' -e'FLUSH PRIVILEGES;'
fi

# Placeholder file in /opt
PLACEHOLDER="/opt/.qstats2_placeholder"

# Remove placeholder file if it exists and /opt/qstats2 is the only directory
if [ -f "$PLACEHOLDER" ]; then
    # Count the number of items in /opt
    ITEM_COUNT=$(find /opt -mindepth 1 -maxdepth 1 | wc -l)
    
    # Check if /opt/qstats2 is the only item
    if [ "$ITEM_COUNT" -eq 1 ]; then
        rm -f "$PLACEHOLDER"
    fi
fi

echo 'Qstats Removed Sucessfully'

exit 0

