#!/bin/bash

mysql -u'root' < /opt/qstats2/qstats2.sql

# Placeholder file in /opt
PLACEHOLDER="/opt/.qstats2_placeholder"

# Create placeholder file
if [ ! -f "$PLACEHOLDER" ]; then
    touch "$PLACEHOLDER"
fi

echo 'Qstats Installed successfully, Cleaning up some storage'

rm -rf /opt/qstats2
